"use client";
/* eslint-disable @next/next/no-img-element -- These local portraits are tiny pre-compressed assets; an image runtime adds no useful optimization. */
import SiteFrame,{PageHero} from "../components/SiteFrame";
import ProgressiveImage from "../components/ProgressiveImage";
import VideoPlaceholder from "../components/VideoPlaceholder";
import useLanguage from "../components/useLanguage";
const journey=[
  ["2022","跨境项目正式启动，海外团队同步开始筹建。团队从市场研究、平台运营与本地内容切入，为东南亚业务落地建立基础。","Our global commerce project launched and the overseas team began taking shape. Market research, platform operations and local content laid the foundation for Southeast Asia."],
  ["2023","福州事为电子商务有限公司正式运营，聚焦Shopee、TikTok等主流平台。首年即在服饰垂直类目实现市场占有率TOP3。","Fuzhou SellsWell E-commerce began operations, focusing on Shopee, TikTok and other leading platforms, reaching a Top 3 market position in its apparel vertical in the first year."],
  ["2024","推行多平台、多类目策略，设立亚马逊事业部并进入美国家居市场；汽摩配与文胸业务同步启动，形成更丰富的业务矩阵。","We adopted a multi-platform, multi-category strategy, formed an Amazon division and entered the US home market while launching automotive parts and lingerie businesses."],
  ["2025","与广州八千里路达成战略合作，进一步整合运营、技术和供应链能力。业务覆盖泰国、印尼、马来西亚等市场，事为电商GMV同比增长5倍。","A strategic partnership with Guangzhou 8000 Miles integrated operations, technology and supply chain capabilities. Business expanded across Thailand, Indonesia, Malaysia and beyond, with SellsWell GMV growing fivefold year over year."],
  ["2026","启动巴西市场与本地化仓储体系建设，持续链接国内及海外本地供应链。全球预估GMV为1–2亿元，迈入全球化布局新阶段。","We began building our Brazil market and localized warehousing network while connecting Chinese and overseas supply chains. Estimated global GMV is RMB 100–200 million as we enter a new stage of globalization."],
];
const leaders=[
  ["Rick Liu","创始人 / CEO","Founder / CEO","拥有10年互联网产品研发经验与7年互联网出海经历。曾任阿里巴巴eWTP基金旗下出海企业高级产品经理，深度参与东南亚市场布局；也曾在腾讯投资的头部汽车媒体企业及格力科技部门主导电商平台设计。如今专注于用中国供应链能力服务全球消费者，坚持长期主义，把事情做到极致。","With 10 years in internet product development and seven years in global expansion, Rick previously served as a senior product manager at an eWTP Fund-backed company and led e-commerce platform design at a Tencent-invested automotive media company and Gree's technology division. He now focuses on bringing Chinese supply chain strengths to global consumers through long-term thinking and rigorous execution.","/assets/leaders/rick-liu.webp"],
  ["Jeff Chen","广州八千里路信息科技公司创始人 / 合伙人","Founder of Guangzhou 8000 Miles Information Technology / Partner","中国传媒大学广告学硕士，拥有14年互联网行业经验与6年出海团队建设经验。曾管理上百人研发团队，担任出海互联网公司COO；2020年在东南亚组建超50人的本地化内容团队，打造TikTok亿级内容矩阵，并在7个月内通过SEO将电商网站提升至月活300万。现主攻AI应用、内容增长及海外市场业务。","Jeff holds a master's degree in advertising from the Communication University of China and has 14 years of internet industry experience, including six years building overseas teams. He has managed a 100+ person R&D organization, served as COO of a global internet company, built a 50+ person localized content team in Southeast Asia and scaled a TikTok content network to hundreds of millions of views. He now focuses on AI applications, content growth and overseas markets.","/assets/leaders/jeff-chen.jpg"],
  ["Zico","合伙人 / 高级运营经理","Partner / Senior Operations Manager","大学期间开始钻研电商平台打法，从实习生用两年成长为高级运营经理，是公司从0到1的核心成员。他参与完成从首笔订单、爆款打造到单月GMV突破千万的全过程，精通平台策略、流量运营、用户增长与项目统筹。现已通过公司持股平台成为合伙人，与团队共享长期成长。","Zico began studying e-commerce platforms at university and progressed from intern to senior operations manager in two years. A core member from day one, he helped take the business from its first order to breakout products and monthly GMV above RMB 10 million. He is now a partner through the company's employee ownership platform.","/assets/leaders/zico.webp"],
  ["Ivy","运营经理","Operations Manager","2024年加入团队，在公司高速扩张中从实习生成长为运营经理。她熟悉电商全链路运营，覆盖日常运维、流量结构优化与业绩提升，能够独立完成项目从规划到执行的闭环管理。认真严谨、积极进取，是公司人才培养与内部晋升机制的真实缩影。","Ivy joined in 2024 and grew from intern to operations manager during a period of rapid expansion. She manages the full e-commerce operating cycle—from daily operations and traffic optimization to performance improvement—and independently leads projects from planning through execution.","/assets/leaders/ivy.webp"],
];
export default function About(){const en=useLanguage()==="en";return <SiteFrame active="about">
  <PageHero eyebrow="ABOUT SELLSWELL" title={en?<>Do the right things for the long term.<br/>Deliver real results.</>:<>长期做正确的事，<br/>把事情做成</>} description={en?"We believe value for money should never mean low quality. Through better products and professional operations, SellsWell helps the world rediscover quality from China.":"我们相信高性价比不等于低价。事为希望通过优质产品与专业经营，让世界重新认识中国品质。"} media={<VideoPlaceholder/>}/>
  <section className="inner-section intro-grid"><div><div className="section-kicker">WHO WE ARE</div><h2>{en?"About SellsWell":"关于事为"}</h2></div><div className="about-copy">{(en?[
    "SellsWell's global commerce project began in 2022 and was formally established in Fuzhou in 2023. We are deeply rooted in Southeast Asia and continue to expand across Europe, the United States, Mexico and Brazil, connecting market insight, platform operations, content growth and local fulfillment through Chinese supply chains and localized execution.",
    "We operate on Shopee, Lazada, TikTok, Amazon and other leading platforms across automotive parts, home cleaning, home and living, lingerie and other priority categories. Frontline operations have helped us build capabilities in assortment management, breakout products, brand building, overseas warehousing and local compliance, supported by proprietary AI systems.",
    "Fuzhou SellsWell E-commerce Co., Ltd. serves as the website and self-operated commerce entity. Fuzhou 8000 Miles E-commerce Co., Ltd. manages domestic and overseas supply chain partnerships. Guangzhou 8000 Miles Information Technology Co., Ltd. focuses on European and US commerce, AI applications, content growth and overseas markets. The three entities collaborate around one shared vision.",
    "We do not define Chinese manufacturing by low prices or chase short-lived growth. We aim to help the world rediscover quality from China through excellent value and long-term professional operations—creating sustainable value with supply chain partners and our team."
  ]:[
    "事为电商的跨境项目于2022年启动，2023年在福州正式注册运营。我们深耕东南亚，并持续布局欧洲、美国、墨西哥与巴西，以“中国供应链＋本地化运营”为核心，把真实的海外市场判断、平台经营、内容增长和本地履约连接成完整闭环。",
    "公司长期运营Shopee、Lazada、TikTok、Amazon等主流平台，覆盖汽摩配、家清用品、家居生活用品、文胸等重点类目。一路走来，我们从自营电商的一线实战出发，逐步沉淀出精铺运营、爆款打造、品牌建设、海外仓储与本地合规等能力，并通过自研AI系统持续提升内容生产和精细化运营效率。",
    "公司以福州事为电子商务有限公司为官网及自营电商主体；福州八千里路电子商务有限公司负责国内与海外供应链合作；广州八千里路信息科技有限公司聚焦欧美电商运营、AI应用、内容增长及海外市场业务。三个主体围绕同一业务愿景协同，让好产品、专业运营、智能技术与全球履约彼此支撑。",
    "我们不以低价定义中国制造，也不追逐昙花一现的增长。事为希望用高性价比的优质商品和长期专业经营，让世界重新认识中国品质；同时与供应链伙伴、团队成员共同创造并分享可持续的价值。"
  ]).map(x=><p key={x}>{x}</p>)}</div></section>
  <section className="inner-section values-section"><div className="section-kicker">WHAT WE BELIEVE</div><div className="split-title"><h2>{en?"Long-term · Pragmatic · Progress · Proactive":"长远 · 务实 · 精进 · 主动"}</h2><p>{en?"Values are not slogans on a wall. They guide how we approach markets, partners and every responsibility.":"价值观不是写在墙上的口号，而是我们面对市场、伙伴和每一次任务时共同遵循的做事方式。"}</p></div><div className="value-grid">{[["01 / LONG-TERM","长远","Long-term","不盲从，不追逐短期暴利；选择能够持续积累、产生长期复利的产品、能力与合作关系。","We choose products, capabilities and partnerships that compound over time instead of chasing short-term windfalls."],["02 / PRAGMATIC","务实","Pragmatic","不美化报表和问题。尊重事实，看见什么就说什么，有问题就直面并推动解决。","We respect facts, speak honestly about problems and drive them toward resolution."],["03 / PROGRESS","精进","Progress","永葆好奇心，不怕折腾；不断复盘、学习和优化，让今天比昨天进步一点。","We stay curious, keep learning and improve through constant review and iteration."],["04 / PROACTIVE","主动","Proactive","不等待安排。主动发现问题、解决卡点，也把每一次任务都当作自己成长的机会。","We identify problems, remove blockers and treat every responsibility as an opportunity to grow."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{en?x[2]:x[1]}</h3><p>{en?x[4]:x[3]}</p></article>)}</div></section>
  <section className="inner-section soft journey-section"><div className="section-kicker">OUR JOURNEY</div><h2>{en?"Our journey":"发展历程"}</h2><div className="timeline">{journey.map(x=><article key={x[0]}><b>{x[0]}</b><i aria-hidden="true"/><p>{en?x[2]:x[1]}</p></article>)}</div></section>
  <section className="inner-section"><div className="section-kicker">LEADERSHIP</div><h2>{en?"Core team":"核心团队"}</h2><div className="people-grid">{leaders.map(x=><article key={x[0]}><div className="leader-portrait"><img src={`${x[5]}?v=20260822-2`} alt={`${x[0]} ${en?"portrait":"头像"}`}/></div><h3>{x[0]}</h3><b>{en?x[2]:x[1]}</b><p>{en?x[4]:x[3]}</p></article>)}</div></section>
  <section className="photo-story"><ProgressiveImage src="/assets/team/office.jpg" optimizedBase="/assets/optimized/team/office" width={1672} height={941} sizes="(max-width: 900px) 50vw, 50vw" alt={en?"SellsWell office":"事为电商办公环境"}/><ProgressiveImage src="/assets/team/reception.png" optimizedBase="/assets/optimized/team/reception" width={2848} height={1600} sizes="(max-width: 900px) 50vw, 25vw" alt={en?"SellsWell and 8000 Miles reception":"事为电商与八千里路公司门头"}/><ProgressiveImage src="/assets/team/annual-recognition.jpg" optimizedBase="/assets/optimized/team/annual-recognition" width={1672} height={941} sizes="(max-width: 900px) 50vw, 25vw" alt={en?"Annual recognition event":"事为电商年终表彰活动"}/><ProgressiveImage src="/assets/team/recognition-speech.jpg" optimizedBase="/assets/optimized/team/recognition-speech" width={2816} height={1584} sizes="(max-width: 900px) 50vw, 50vw" alt={en?"Employee recognition and sharing":"员工表彰与分享"}/></section>
  <section className="inner-section office-row"><div><b>{en?"Fuzhou Office":"福州办公室"}</b><p>{en?"Room 301, Gehang Electronics Building, Innovation Park, Minhou County, Fuzhou, Fujian":"福建省福州市闽侯县高新区创新园13栋歌航电子大厦301室"}</p></div><div><b>{en?"Guangzhou Office":"广州办公室"}</b><p>{en?"Room 305, Building 1, Chuangxing Port, 91 Baishashui Road, Tianhe District, Guangzhou":"广东省广州市天河区白沙水路91号创兴港1栋305室"}</p></div></section>
</SiteFrame>}
